/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TermsAndConditionsClubRouteImport } from './routes/terms-and-conditions-club'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PurchaseTermsRouteImport } from './routes/purchase-terms'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as OauthRouteImport } from './routes/oauth'
import { Route as LegalNoticeRouteImport } from './routes/legal-notice'
import { Route as IncidentRouteImport } from './routes/incident'
import { Route as ForgotChangeRouteImport } from './routes/forgot-change'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as AuthSuccessRouteImport } from './routes/auth-success'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RrppSlugRouteImport } from './routes/rrpp.$slug'
import { Route as EventSlugRouteImport } from './routes/event.$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutCancelRouteImport } from './routes/checkout.cancel'
import { Route as ArtistSlugRouteImport } from './routes/artist.$slug'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedWalletUpcomingRouteImport } from './routes/_authenticated/wallet.upcoming'
import { Route as AuthenticatedWalletPastRouteImport } from './routes/_authenticated/wallet.past'
import { Route as AuthenticatedWalletKardsRouteImport } from './routes/_authenticated/wallet.kards'
import { Route as AuthenticatedWalletTransactionIdRouteImport } from './routes/_authenticated/wallet.$transactionId'
import { Route as AuthenticatedWalletTransactionIdItemIdRouteImport } from './routes/_authenticated/wallet.$transactionId.$itemId'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsClubRoute = TermsAndConditionsClubRouteImport.update({
  id: '/terms-and-conditions-club',
  path: '/terms-and-conditions-club',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseTermsRoute = PurchaseTermsRouteImport.update({
  id: '/purchase-terms',
  path: '/purchase-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthRoute = OauthRouteImport.update({
  id: '/oauth',
  path: '/oauth',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalNoticeRoute = LegalNoticeRouteImport.update({
  id: '/legal-notice',
  path: '/legal-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentRoute = IncidentRouteImport.update({
  id: '/incident',
  path: '/incident',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotChangeRoute = ForgotChangeRouteImport.update({
  id: '/forgot-change',
  path: '/forgot-change',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSuccessRoute = AuthSuccessRouteImport.update({
  id: '/auth-success',
  path: '/auth-success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RrppSlugRoute = RrppSlugRouteImport.update({
  id: '/rrpp/$slug',
  path: '/rrpp/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventSlugRoute = EventSlugRouteImport.update({
  id: '/event/$slug',
  path: '/event/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/checkout/cancel',
  path: '/checkout/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistSlugRoute = ArtistSlugRouteImport.update({
  id: '/artist/$slug',
  path: '/artist/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWalletUpcomingRoute =
  AuthenticatedWalletUpcomingRouteImport.update({
    id: '/upcoming',
    path: '/upcoming',
    getParentRoute: () => AuthenticatedWalletRoute,
  } as any)
const AuthenticatedWalletPastRoute = AuthenticatedWalletPastRouteImport.update({
  id: '/past',
  path: '/past',
  getParentRoute: () => AuthenticatedWalletRoute,
} as any)
const AuthenticatedWalletKardsRoute =
  AuthenticatedWalletKardsRouteImport.update({
    id: '/kards',
    path: '/kards',
    getParentRoute: () => AuthenticatedWalletRoute,
  } as any)
const AuthenticatedWalletTransactionIdRoute =
  AuthenticatedWalletTransactionIdRouteImport.update({
    id: '/$transactionId',
    path: '/$transactionId',
    getParentRoute: () => AuthenticatedWalletRoute,
  } as any)
const AuthenticatedWalletTransactionIdItemIdRoute =
  AuthenticatedWalletTransactionIdItemIdRouteImport.update({
    id: '/$itemId',
    path: '/$itemId',
    getParentRoute: () => AuthenticatedWalletTransactionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-success': typeof AuthSuccessRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/forgot': typeof ForgotRoute
  '/forgot-change': typeof ForgotChangeRoute
  '/incident': typeof IncidentRoute
  '/legal-notice': typeof LegalNoticeRoute
  '/oauth': typeof OauthRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/purchase-terms': typeof PurchaseTermsRoute
  '/register': typeof RegisterRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/terms-and-conditions-club': typeof TermsAndConditionsClubRoute
  '/verify': typeof VerifyRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/wallet': typeof AuthenticatedWalletRouteWithChildren
  '/artist/$slug': typeof ArtistSlugRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/event/$slug': typeof EventSlugRoute
  '/rrpp/$slug': typeof RrppSlugRoute
  '/wallet/$transactionId': typeof AuthenticatedWalletTransactionIdRouteWithChildren
  '/wallet/kards': typeof AuthenticatedWalletKardsRoute
  '/wallet/past': typeof AuthenticatedWalletPastRoute
  '/wallet/upcoming': typeof AuthenticatedWalletUpcomingRoute
  '/wallet/$transactionId/$itemId': typeof AuthenticatedWalletTransactionIdItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-success': typeof AuthSuccessRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/forgot': typeof ForgotRoute
  '/forgot-change': typeof ForgotChangeRoute
  '/incident': typeof IncidentRoute
  '/legal-notice': typeof LegalNoticeRoute
  '/oauth': typeof OauthRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/purchase-terms': typeof PurchaseTermsRoute
  '/register': typeof RegisterRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/terms-and-conditions-club': typeof TermsAndConditionsClubRoute
  '/verify': typeof VerifyRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/wallet': typeof AuthenticatedWalletRouteWithChildren
  '/artist/$slug': typeof ArtistSlugRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/event/$slug': typeof EventSlugRoute
  '/rrpp/$slug': typeof RrppSlugRoute
  '/wallet/$transactionId': typeof AuthenticatedWalletTransactionIdRouteWithChildren
  '/wallet/kards': typeof AuthenticatedWalletKardsRoute
  '/wallet/past': typeof AuthenticatedWalletPastRoute
  '/wallet/upcoming': typeof AuthenticatedWalletUpcomingRoute
  '/wallet/$transactionId/$itemId': typeof AuthenticatedWalletTransactionIdItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/auth-success': typeof AuthSuccessRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/forgot': typeof ForgotRoute
  '/forgot-change': typeof ForgotChangeRoute
  '/incident': typeof IncidentRoute
  '/legal-notice': typeof LegalNoticeRoute
  '/oauth': typeof OauthRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/purchase-terms': typeof PurchaseTermsRoute
  '/register': typeof RegisterRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/terms-and-conditions-club': typeof TermsAndConditionsClubRoute
  '/verify': typeof VerifyRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRouteWithChildren
  '/artist/$slug': typeof ArtistSlugRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/event/$slug': typeof EventSlugRoute
  '/rrpp/$slug': typeof RrppSlugRoute
  '/_authenticated/wallet/$transactionId': typeof AuthenticatedWalletTransactionIdRouteWithChildren
  '/_authenticated/wallet/kards': typeof AuthenticatedWalletKardsRoute
  '/_authenticated/wallet/past': typeof AuthenticatedWalletPastRoute
  '/_authenticated/wallet/upcoming': typeof AuthenticatedWalletUpcomingRoute
  '/_authenticated/wallet/$transactionId/$itemId': typeof AuthenticatedWalletTransactionIdItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth-success'
    | '/cookie-policy'
    | '/forgot'
    | '/forgot-change'
    | '/incident'
    | '/legal-notice'
    | '/oauth'
    | '/privacy-policy'
    | '/purchase-terms'
    | '/register'
    | '/terms-and-conditions'
    | '/terms-and-conditions-club'
    | '/verify'
    | '/profile'
    | '/wallet'
    | '/artist/$slug'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/event/$slug'
    | '/rrpp/$slug'
    | '/wallet/$transactionId'
    | '/wallet/kards'
    | '/wallet/past'
    | '/wallet/upcoming'
    | '/wallet/$transactionId/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth-success'
    | '/cookie-policy'
    | '/forgot'
    | '/forgot-change'
    | '/incident'
    | '/legal-notice'
    | '/oauth'
    | '/privacy-policy'
    | '/purchase-terms'
    | '/register'
    | '/terms-and-conditions'
    | '/terms-and-conditions-club'
    | '/verify'
    | '/profile'
    | '/wallet'
    | '/artist/$slug'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/event/$slug'
    | '/rrpp/$slug'
    | '/wallet/$transactionId'
    | '/wallet/kards'
    | '/wallet/past'
    | '/wallet/upcoming'
    | '/wallet/$transactionId/$itemId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/auth-success'
    | '/cookie-policy'
    | '/forgot'
    | '/forgot-change'
    | '/incident'
    | '/legal-notice'
    | '/oauth'
    | '/privacy-policy'
    | '/purchase-terms'
    | '/register'
    | '/terms-and-conditions'
    | '/terms-and-conditions-club'
    | '/verify'
    | '/_authenticated/profile'
    | '/_authenticated/wallet'
    | '/artist/$slug'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/event/$slug'
    | '/rrpp/$slug'
    | '/_authenticated/wallet/$transactionId'
    | '/_authenticated/wallet/kards'
    | '/_authenticated/wallet/past'
    | '/_authenticated/wallet/upcoming'
    | '/_authenticated/wallet/$transactionId/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  AuthSuccessRoute: typeof AuthSuccessRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  ForgotRoute: typeof ForgotRoute
  ForgotChangeRoute: typeof ForgotChangeRoute
  IncidentRoute: typeof IncidentRoute
  LegalNoticeRoute: typeof LegalNoticeRoute
  OauthRoute: typeof OauthRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  PurchaseTermsRoute: typeof PurchaseTermsRoute
  RegisterRoute: typeof RegisterRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TermsAndConditionsClubRoute: typeof TermsAndConditionsClubRoute
  VerifyRoute: typeof VerifyRoute
  ArtistSlugRoute: typeof ArtistSlugRoute
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  EventSlugRoute: typeof EventSlugRoute
  RrppSlugRoute: typeof RrppSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions-club': {
      id: '/terms-and-conditions-club'
      path: '/terms-and-conditions-club'
      fullPath: '/terms-and-conditions-club'
      preLoaderRoute: typeof TermsAndConditionsClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-terms': {
      id: '/purchase-terms'
      path: '/purchase-terms'
      fullPath: '/purchase-terms'
      preLoaderRoute: typeof PurchaseTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth': {
      id: '/oauth'
      path: '/oauth'
      fullPath: '/oauth'
      preLoaderRoute: typeof OauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal-notice': {
      id: '/legal-notice'
      path: '/legal-notice'
      fullPath: '/legal-notice'
      preLoaderRoute: typeof LegalNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incident': {
      id: '/incident'
      path: '/incident'
      fullPath: '/incident'
      preLoaderRoute: typeof IncidentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-change': {
      id: '/forgot-change'
      path: '/forgot-change'
      fullPath: '/forgot-change'
      preLoaderRoute: typeof ForgotChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-success': {
      id: '/auth-success'
      path: '/auth-success'
      fullPath: '/auth-success'
      preLoaderRoute: typeof AuthSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rrpp/$slug': {
      id: '/rrpp/$slug'
      path: '/rrpp/$slug'
      fullPath: '/rrpp/$slug'
      preLoaderRoute: typeof RrppSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$slug': {
      id: '/event/$slug'
      path: '/event/$slug'
      fullPath: '/event/$slug'
      preLoaderRoute: typeof EventSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/checkout/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$slug': {
      id: '/artist/$slug'
      path: '/artist/$slug'
      fullPath: '/artist/$slug'
      preLoaderRoute: typeof ArtistSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/wallet/upcoming': {
      id: '/_authenticated/wallet/upcoming'
      path: '/upcoming'
      fullPath: '/wallet/upcoming'
      preLoaderRoute: typeof AuthenticatedWalletUpcomingRouteImport
      parentRoute: typeof AuthenticatedWalletRoute
    }
    '/_authenticated/wallet/past': {
      id: '/_authenticated/wallet/past'
      path: '/past'
      fullPath: '/wallet/past'
      preLoaderRoute: typeof AuthenticatedWalletPastRouteImport
      parentRoute: typeof AuthenticatedWalletRoute
    }
    '/_authenticated/wallet/kards': {
      id: '/_authenticated/wallet/kards'
      path: '/kards'
      fullPath: '/wallet/kards'
      preLoaderRoute: typeof AuthenticatedWalletKardsRouteImport
      parentRoute: typeof AuthenticatedWalletRoute
    }
    '/_authenticated/wallet/$transactionId': {
      id: '/_authenticated/wallet/$transactionId'
      path: '/$transactionId'
      fullPath: '/wallet/$transactionId'
      preLoaderRoute: typeof AuthenticatedWalletTransactionIdRouteImport
      parentRoute: typeof AuthenticatedWalletRoute
    }
    '/_authenticated/wallet/$transactionId/$itemId': {
      id: '/_authenticated/wallet/$transactionId/$itemId'
      path: '/$itemId'
      fullPath: '/wallet/$transactionId/$itemId'
      preLoaderRoute: typeof AuthenticatedWalletTransactionIdItemIdRouteImport
      parentRoute: typeof AuthenticatedWalletTransactionIdRoute
    }
  }
}

interface AuthenticatedWalletTransactionIdRouteChildren {
  AuthenticatedWalletTransactionIdItemIdRoute: typeof AuthenticatedWalletTransactionIdItemIdRoute
}

const AuthenticatedWalletTransactionIdRouteChildren: AuthenticatedWalletTransactionIdRouteChildren =
  {
    AuthenticatedWalletTransactionIdItemIdRoute:
      AuthenticatedWalletTransactionIdItemIdRoute,
  }

const AuthenticatedWalletTransactionIdRouteWithChildren =
  AuthenticatedWalletTransactionIdRoute._addFileChildren(
    AuthenticatedWalletTransactionIdRouteChildren,
  )

interface AuthenticatedWalletRouteChildren {
  AuthenticatedWalletTransactionIdRoute: typeof AuthenticatedWalletTransactionIdRouteWithChildren
  AuthenticatedWalletKardsRoute: typeof AuthenticatedWalletKardsRoute
  AuthenticatedWalletPastRoute: typeof AuthenticatedWalletPastRoute
  AuthenticatedWalletUpcomingRoute: typeof AuthenticatedWalletUpcomingRoute
}

const AuthenticatedWalletRouteChildren: AuthenticatedWalletRouteChildren = {
  AuthenticatedWalletTransactionIdRoute:
    AuthenticatedWalletTransactionIdRouteWithChildren,
  AuthenticatedWalletKardsRoute: AuthenticatedWalletKardsRoute,
  AuthenticatedWalletPastRoute: AuthenticatedWalletPastRoute,
  AuthenticatedWalletUpcomingRoute: AuthenticatedWalletUpcomingRoute,
}

const AuthenticatedWalletRouteWithChildren =
  AuthenticatedWalletRoute._addFileChildren(AuthenticatedWalletRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  AuthSuccessRoute: AuthSuccessRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  ForgotRoute: ForgotRoute,
  ForgotChangeRoute: ForgotChangeRoute,
  IncidentRoute: IncidentRoute,
  LegalNoticeRoute: LegalNoticeRoute,
  OauthRoute: OauthRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  PurchaseTermsRoute: PurchaseTermsRoute,
  RegisterRoute: RegisterRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TermsAndConditionsClubRoute: TermsAndConditionsClubRoute,
  VerifyRoute: VerifyRoute,
  ArtistSlugRoute: ArtistSlugRoute,
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  EventSlugRoute: EventSlugRoute,
  RrppSlugRoute: RrppSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
