/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OauthRouteImport } from './routes/oauth'
import { Route as IncidentRouteImport } from './routes/incident'
import { Route as ForgotChangeRouteImport } from './routes/forgot-change'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as AuthSuccessRouteImport } from './routes/auth-success'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedManagerKlaudiaRouteImport } from './routes/_authenticated/manager/klaudia'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthRoute = OauthRouteImport.update({
  id: '/oauth',
  path: '/oauth',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentRoute = IncidentRouteImport.update({
  id: '/incident',
  path: '/incident',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotChangeRoute = ForgotChangeRouteImport.update({
  id: '/forgot-change',
  path: '/forgot-change',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSuccessRoute = AuthSuccessRouteImport.update({
  id: '/auth-success',
  path: '/auth-success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedManagerKlaudiaRoute =
  AuthenticatedManagerKlaudiaRouteImport.update({
    id: '/manager/klaudia',
    path: '/manager/klaudia',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth-success': typeof AuthSuccessRoute
  '/forgot': typeof ForgotRoute
  '/forgot-change': typeof ForgotChangeRoute
  '/incident': typeof IncidentRoute
  '/oauth': typeof OauthRoute
  '/register': typeof RegisterRoute
  '/verify': typeof VerifyRoute
  '/manager/klaudia': typeof AuthenticatedManagerKlaudiaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-success': typeof AuthSuccessRoute
  '/forgot': typeof ForgotRoute
  '/forgot-change': typeof ForgotChangeRoute
  '/incident': typeof IncidentRoute
  '/oauth': typeof OauthRoute
  '/register': typeof RegisterRoute
  '/verify': typeof VerifyRoute
  '/manager/klaudia': typeof AuthenticatedManagerKlaudiaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth-success': typeof AuthSuccessRoute
  '/forgot': typeof ForgotRoute
  '/forgot-change': typeof ForgotChangeRoute
  '/incident': typeof IncidentRoute
  '/oauth': typeof OauthRoute
  '/register': typeof RegisterRoute
  '/verify': typeof VerifyRoute
  '/_authenticated/manager/klaudia': typeof AuthenticatedManagerKlaudiaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth-success'
    | '/forgot'
    | '/forgot-change'
    | '/incident'
    | '/oauth'
    | '/register'
    | '/verify'
    | '/manager/klaudia'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-success'
    | '/forgot'
    | '/forgot-change'
    | '/incident'
    | '/oauth'
    | '/register'
    | '/verify'
    | '/manager/klaudia'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth-success'
    | '/forgot'
    | '/forgot-change'
    | '/incident'
    | '/oauth'
    | '/register'
    | '/verify'
    | '/_authenticated/manager/klaudia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthSuccessRoute: typeof AuthSuccessRoute
  ForgotRoute: typeof ForgotRoute
  ForgotChangeRoute: typeof ForgotChangeRoute
  IncidentRoute: typeof IncidentRoute
  OauthRoute: typeof OauthRoute
  RegisterRoute: typeof RegisterRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth': {
      id: '/oauth'
      path: '/oauth'
      fullPath: '/oauth'
      preLoaderRoute: typeof OauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incident': {
      id: '/incident'
      path: '/incident'
      fullPath: '/incident'
      preLoaderRoute: typeof IncidentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-change': {
      id: '/forgot-change'
      path: '/forgot-change'
      fullPath: '/forgot-change'
      preLoaderRoute: typeof ForgotChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-success': {
      id: '/auth-success'
      path: '/auth-success'
      fullPath: '/auth-success'
      preLoaderRoute: typeof AuthSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/manager/klaudia': {
      id: '/_authenticated/manager/klaudia'
      path: '/manager/klaudia'
      fullPath: '/manager/klaudia'
      preLoaderRoute: typeof AuthenticatedManagerKlaudiaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedManagerKlaudiaRoute: typeof AuthenticatedManagerKlaudiaRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedManagerKlaudiaRoute: AuthenticatedManagerKlaudiaRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthSuccessRoute: AuthSuccessRoute,
  ForgotRoute: ForgotRoute,
  ForgotChangeRoute: ForgotChangeRoute,
  IncidentRoute: IncidentRoute,
  OauthRoute: OauthRoute,
  RegisterRoute: RegisterRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
