/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OauthRouteImport } from './routes/oauth'
import { Route as IncidentRouteImport } from './routes/incident'
import { Route as ForgotChangeRouteImport } from './routes/forgot-change'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as AuthSuccessRouteImport } from './routes/auth-success'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RrrppSlugRouteImport } from './routes/rrrpp.$slug'
import { Route as EventSlugRouteImport } from './routes/event.$slug'
import { Route as ArtistSlugRouteImport } from './routes/artist.$slug'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthRoute = OauthRouteImport.update({
  id: '/oauth',
  path: '/oauth',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentRoute = IncidentRouteImport.update({
  id: '/incident',
  path: '/incident',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotChangeRoute = ForgotChangeRouteImport.update({
  id: '/forgot-change',
  path: '/forgot-change',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSuccessRoute = AuthSuccessRouteImport.update({
  id: '/auth-success',
  path: '/auth-success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RrrppSlugRoute = RrrppSlugRouteImport.update({
  id: '/rrrpp/$slug',
  path: '/rrrpp/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventSlugRoute = EventSlugRouteImport.update({
  id: '/event/$slug',
  path: '/event/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistSlugRoute = ArtistSlugRouteImport.update({
  id: '/artist/$slug',
  path: '/artist/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-success': typeof AuthSuccessRoute
  '/forgot': typeof ForgotRoute
  '/forgot-change': typeof ForgotChangeRoute
  '/incident': typeof IncidentRoute
  '/oauth': typeof OauthRoute
  '/register': typeof RegisterRoute
  '/verify': typeof VerifyRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/artist/$slug': typeof ArtistSlugRoute
  '/event/$slug': typeof EventSlugRoute
  '/rrrpp/$slug': typeof RrrppSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-success': typeof AuthSuccessRoute
  '/forgot': typeof ForgotRoute
  '/forgot-change': typeof ForgotChangeRoute
  '/incident': typeof IncidentRoute
  '/oauth': typeof OauthRoute
  '/register': typeof RegisterRoute
  '/verify': typeof VerifyRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/artist/$slug': typeof ArtistSlugRoute
  '/event/$slug': typeof EventSlugRoute
  '/rrrpp/$slug': typeof RrrppSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/auth-success': typeof AuthSuccessRoute
  '/forgot': typeof ForgotRoute
  '/forgot-change': typeof ForgotChangeRoute
  '/incident': typeof IncidentRoute
  '/oauth': typeof OauthRoute
  '/register': typeof RegisterRoute
  '/verify': typeof VerifyRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/artist/$slug': typeof ArtistSlugRoute
  '/event/$slug': typeof EventSlugRoute
  '/rrrpp/$slug': typeof RrrppSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth-success'
    | '/forgot'
    | '/forgot-change'
    | '/incident'
    | '/oauth'
    | '/register'
    | '/verify'
    | '/profile'
    | '/wallet'
    | '/artist/$slug'
    | '/event/$slug'
    | '/rrrpp/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth-success'
    | '/forgot'
    | '/forgot-change'
    | '/incident'
    | '/oauth'
    | '/register'
    | '/verify'
    | '/profile'
    | '/wallet'
    | '/artist/$slug'
    | '/event/$slug'
    | '/rrrpp/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/auth-success'
    | '/forgot'
    | '/forgot-change'
    | '/incident'
    | '/oauth'
    | '/register'
    | '/verify'
    | '/_authenticated/profile'
    | '/_authenticated/wallet'
    | '/artist/$slug'
    | '/event/$slug'
    | '/rrrpp/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  AuthSuccessRoute: typeof AuthSuccessRoute
  ForgotRoute: typeof ForgotRoute
  ForgotChangeRoute: typeof ForgotChangeRoute
  IncidentRoute: typeof IncidentRoute
  OauthRoute: typeof OauthRoute
  RegisterRoute: typeof RegisterRoute
  VerifyRoute: typeof VerifyRoute
  ArtistSlugRoute: typeof ArtistSlugRoute
  EventSlugRoute: typeof EventSlugRoute
  RrrppSlugRoute: typeof RrrppSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth': {
      id: '/oauth'
      path: '/oauth'
      fullPath: '/oauth'
      preLoaderRoute: typeof OauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incident': {
      id: '/incident'
      path: '/incident'
      fullPath: '/incident'
      preLoaderRoute: typeof IncidentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-change': {
      id: '/forgot-change'
      path: '/forgot-change'
      fullPath: '/forgot-change'
      preLoaderRoute: typeof ForgotChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-success': {
      id: '/auth-success'
      path: '/auth-success'
      fullPath: '/auth-success'
      preLoaderRoute: typeof AuthSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rrrpp/$slug': {
      id: '/rrrpp/$slug'
      path: '/rrrpp/$slug'
      fullPath: '/rrrpp/$slug'
      preLoaderRoute: typeof RrrppSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$slug': {
      id: '/event/$slug'
      path: '/event/$slug'
      fullPath: '/event/$slug'
      preLoaderRoute: typeof EventSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$slug': {
      id: '/artist/$slug'
      path: '/artist/$slug'
      fullPath: '/artist/$slug'
      preLoaderRoute: typeof ArtistSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  AuthSuccessRoute: AuthSuccessRoute,
  ForgotRoute: ForgotRoute,
  ForgotChangeRoute: ForgotChangeRoute,
  IncidentRoute: IncidentRoute,
  OauthRoute: OauthRoute,
  RegisterRoute: RegisterRoute,
  VerifyRoute: VerifyRoute,
  ArtistSlugRoute: ArtistSlugRoute,
  EventSlugRoute: EventSlugRoute,
  RrrppSlugRoute: RrrppSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
